# 项目级 Gradle 配置
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX 配置
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin 代码风格
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true


# 允许中文路径
android.overridePathCheck=true

